// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: interfaz.proto
// Protobuf Java Version: 4.30.2

package com.tienda.grpc;

public interface CancelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CancelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transaccion_id = 1;</code>
   * @return The transaccionId.
   */
  java.lang.String getTransaccionId();
  /**
   * <code>string transaccion_id = 1;</code>
   * @return The bytes for transaccionId.
   */
  com.google.protobuf.ByteString
      getTransaccionIdBytes();

  /**
   * <pre>
   * ej: "Stock insuficiente"
   * </pre>
   *
   * <code>string motivo = 2;</code>
   * @return The motivo.
   */
  java.lang.String getMotivo();
  /**
   * <pre>
   * ej: "Stock insuficiente"
   * </pre>
   *
   * <code>string motivo = 2;</code>
   * @return The bytes for motivo.
   */
  com.google.protobuf.ByteString
      getMotivoBytes();
}
