// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: interfaz.proto
// Protobuf Java Version: 4.30.2

package com.tienda.grpc;

public interface CancelEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CancelEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string producto_id = 1;</code>
   * @return The productoId.
   */
  java.lang.String getProductoId();
  /**
   * <code>string producto_id = 1;</code>
   * @return The bytes for productoId.
   */
  com.google.protobuf.ByteString
      getProductoIdBytes();

  /**
   * <pre>
   * ej: "Producto X cancelado por falta de stock"
   * </pre>
   *
   * <code>string descripcion = 2;</code>
   * @return The descripcion.
   */
  java.lang.String getDescripcion();
  /**
   * <pre>
   * ej: "Producto X cancelado por falta de stock"
   * </pre>
   *
   * <code>string descripcion = 2;</code>
   * @return The bytes for descripcion.
   */
  com.google.protobuf.ByteString
      getDescripcionBytes();

  /**
   * <pre>
   * "Cancelado", "Parcial"
   * </pre>
   *
   * <code>string estado = 3;</code>
   * @return The estado.
   */
  java.lang.String getEstado();
  /**
   * <pre>
   * "Cancelado", "Parcial"
   * </pre>
   *
   * <code>string estado = 3;</code>
   * @return The bytes for estado.
   */
  com.google.protobuf.ByteString
      getEstadoBytes();
}
