// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: interfaz.proto
// Protobuf Java Version: 4.30.2

package com.tienda.grpc;

public interface CarritoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarritoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string usuario_id = 1;</code>
   * @return The usuarioId.
   */
  java.lang.String getUsuarioId();
  /**
   * <code>string usuario_id = 1;</code>
   * @return The bytes for usuarioId.
   */
  com.google.protobuf.ByteString
      getUsuarioIdBytes();

  /**
   * <pre>
   * lista de productos (no puede estar vacía)
   * </pre>
   *
   * <code>repeated .Producto items = 2;</code>
   */
  java.util.List<com.tienda.grpc.Producto> 
      getItemsList();
  /**
   * <pre>
   * lista de productos (no puede estar vacía)
   * </pre>
   *
   * <code>repeated .Producto items = 2;</code>
   */
  com.tienda.grpc.Producto getItems(int index);
  /**
   * <pre>
   * lista de productos (no puede estar vacía)
   * </pre>
   *
   * <code>repeated .Producto items = 2;</code>
   */
  int getItemsCount();
  /**
   * <pre>
   * lista de productos (no puede estar vacía)
   * </pre>
   *
   * <code>repeated .Producto items = 2;</code>
   */
  java.util.List<? extends com.tienda.grpc.ProductoOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <pre>
   * lista de productos (no puede estar vacía)
   * </pre>
   *
   * <code>repeated .Producto items = 2;</code>
   */
  com.tienda.grpc.ProductoOrBuilder getItemsOrBuilder(
      int index);
}
