// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: interfaz.proto
// Protobuf Java Version: 4.30.2

package com.tienda.grpc;

public final class Interfaz {
  private Interfaz() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Interfaz.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Producto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Producto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Inventario_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Inventario_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarritoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CarritoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarritoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CarritoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Respuesta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Respuesta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CancelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CancelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CancelEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CancelEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ListarRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016interfaz.proto\"H\n\010Producto\022\n\n\002id\030\001 \001(\t" +
      "\022\016\n\006nombre\030\002 \001(\t\022\016\n\006precio\030\003 \001(\001\022\020\n\010cant" +
      "idad\030\004 \001(\005\"K\n\nInventario\022\023\n\013producto_id\030" +
      "\001 \001(\t\022\016\n\006nombre\030\002 \001(\t\022\030\n\020stock_disponibl" +
      "e\030\003 \001(\005\">\n\016CarritoRequest\022\022\n\nusuario_id\030" +
      "\001 \001(\t\022\030\n\005items\030\002 \003(\0132\t.Producto\"u\n\017Carri" +
      "toResponse\022\026\n\016transaccion_id\030\001 \001(\t\022\022\n\nto" +
      "tal_neto\030\002 \001(\001\022\021\n\timpuestos\030\003 \001(\001\022\023\n\013tot" +
      "al_pagar\030\004 \001(\001\022\016\n\006estado\030\005 \001(\t\"+\n\tRespue" +
      "sta\022\r\n\005exito\030\001 \001(\010\022\017\n\007mensaje\030\002 \001(\t\"7\n\rC" +
      "ancelRequest\022\026\n\016transaccion_id\030\001 \001(\t\022\016\n\006" +
      "motivo\030\002 \001(\t\"G\n\013CancelEvent\022\023\n\013producto_" +
      "id\030\001 \001(\t\022\023\n\013descripcion\030\002 \001(\t\022\016\n\006estado\030" +
      "\003 \001(\t\"\"\n\rListarRequest\022\021\n\tcategoria\030\001 \001(" +
      "\t2\374\001\n\016CarritoService\022(\n\017AgregarProducto\022" +
      "\t.Producto\032\n.Respuesta\022)\n\020EliminarProduc" +
      "to\022\t.Producto\032\n.Respuesta\0224\n\017ProcesarCar" +
      "rito\022\017.CarritoRequest\032\020.CarritoResponse\022" +
      "/\n\rCancelarOrden\022\016.CancelRequest\032\014.Cance" +
      "lEvent0\001\022.\n\017ListarProductos\022\016.ListarRequ" +
      "est\032\t.Producto0\001B\023\n\017com.tienda.grpcP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Producto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Producto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Producto_descriptor,
        new java.lang.String[] { "Id", "Nombre", "Precio", "Cantidad", });
    internal_static_Inventario_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Inventario_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Inventario_descriptor,
        new java.lang.String[] { "ProductoId", "Nombre", "StockDisponible", });
    internal_static_CarritoRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CarritoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CarritoRequest_descriptor,
        new java.lang.String[] { "UsuarioId", "Items", });
    internal_static_CarritoResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CarritoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CarritoResponse_descriptor,
        new java.lang.String[] { "TransaccionId", "TotalNeto", "Impuestos", "TotalPagar", "Estado", });
    internal_static_Respuesta_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Respuesta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Respuesta_descriptor,
        new java.lang.String[] { "Exito", "Mensaje", });
    internal_static_CancelRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CancelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CancelRequest_descriptor,
        new java.lang.String[] { "TransaccionId", "Motivo", });
    internal_static_CancelEvent_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_CancelEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CancelEvent_descriptor,
        new java.lang.String[] { "ProductoId", "Descripcion", "Estado", });
    internal_static_ListarRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ListarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ListarRequest_descriptor,
        new java.lang.String[] { "Categoria", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
