// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: interfaz.proto
// Protobuf Java Version: 4.30.2

package com.tienda.grpc;

/**
 * <pre>
 * Inventario de un producto (stock disponible)
 * </pre>
 *
 * Protobuf type {@code Inventario}
 */
public final class Inventario extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Inventario)
    InventarioOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Inventario.class.getName());
  }
  // Use Inventario.newBuilder() to construct.
  private Inventario(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Inventario() {
    productoId_ = "";
    nombre_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tienda.grpc.Interfaz.internal_static_Inventario_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tienda.grpc.Interfaz.internal_static_Inventario_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tienda.grpc.Inventario.class, com.tienda.grpc.Inventario.Builder.class);
  }

  public static final int PRODUCTO_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object productoId_ = "";
  /**
   * <code>string producto_id = 1;</code>
   * @return The productoId.
   */
  @java.lang.Override
  public java.lang.String getProductoId() {
    java.lang.Object ref = productoId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productoId_ = s;
      return s;
    }
  }
  /**
   * <code>string producto_id = 1;</code>
   * @return The bytes for productoId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductoIdBytes() {
    java.lang.Object ref = productoId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productoId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOMBRE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nombre_ = "";
  /**
   * <code>string nombre = 2;</code>
   * @return The nombre.
   */
  @java.lang.Override
  public java.lang.String getNombre() {
    java.lang.Object ref = nombre_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nombre_ = s;
      return s;
    }
  }
  /**
   * <code>string nombre = 2;</code>
   * @return The bytes for nombre.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNombreBytes() {
    java.lang.Object ref = nombre_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nombre_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STOCK_DISPONIBLE_FIELD_NUMBER = 3;
  private int stockDisponible_ = 0;
  /**
   * <code>int32 stock_disponible = 3;</code>
   * @return The stockDisponible.
   */
  @java.lang.Override
  public int getStockDisponible() {
    return stockDisponible_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(productoId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, productoId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nombre_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, nombre_);
    }
    if (stockDisponible_ != 0) {
      output.writeInt32(3, stockDisponible_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(productoId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, productoId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nombre_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nombre_);
    }
    if (stockDisponible_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, stockDisponible_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tienda.grpc.Inventario)) {
      return super.equals(obj);
    }
    com.tienda.grpc.Inventario other = (com.tienda.grpc.Inventario) obj;

    if (!getProductoId()
        .equals(other.getProductoId())) return false;
    if (!getNombre()
        .equals(other.getNombre())) return false;
    if (getStockDisponible()
        != other.getStockDisponible()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRODUCTO_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProductoId().hashCode();
    hash = (37 * hash) + NOMBRE_FIELD_NUMBER;
    hash = (53 * hash) + getNombre().hashCode();
    hash = (37 * hash) + STOCK_DISPONIBLE_FIELD_NUMBER;
    hash = (53 * hash) + getStockDisponible();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tienda.grpc.Inventario parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tienda.grpc.Inventario parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tienda.grpc.Inventario parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tienda.grpc.Inventario parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tienda.grpc.Inventario parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tienda.grpc.Inventario parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tienda.grpc.Inventario parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tienda.grpc.Inventario parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tienda.grpc.Inventario parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tienda.grpc.Inventario parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tienda.grpc.Inventario parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tienda.grpc.Inventario parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tienda.grpc.Inventario prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Inventario de un producto (stock disponible)
   * </pre>
   *
   * Protobuf type {@code Inventario}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Inventario)
      com.tienda.grpc.InventarioOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tienda.grpc.Interfaz.internal_static_Inventario_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tienda.grpc.Interfaz.internal_static_Inventario_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tienda.grpc.Inventario.class, com.tienda.grpc.Inventario.Builder.class);
    }

    // Construct using com.tienda.grpc.Inventario.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      productoId_ = "";
      nombre_ = "";
      stockDisponible_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tienda.grpc.Interfaz.internal_static_Inventario_descriptor;
    }

    @java.lang.Override
    public com.tienda.grpc.Inventario getDefaultInstanceForType() {
      return com.tienda.grpc.Inventario.getDefaultInstance();
    }

    @java.lang.Override
    public com.tienda.grpc.Inventario build() {
      com.tienda.grpc.Inventario result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tienda.grpc.Inventario buildPartial() {
      com.tienda.grpc.Inventario result = new com.tienda.grpc.Inventario(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tienda.grpc.Inventario result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.productoId_ = productoId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nombre_ = nombre_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.stockDisponible_ = stockDisponible_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tienda.grpc.Inventario) {
        return mergeFrom((com.tienda.grpc.Inventario)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tienda.grpc.Inventario other) {
      if (other == com.tienda.grpc.Inventario.getDefaultInstance()) return this;
      if (!other.getProductoId().isEmpty()) {
        productoId_ = other.productoId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getNombre().isEmpty()) {
        nombre_ = other.nombre_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getStockDisponible() != 0) {
        setStockDisponible(other.getStockDisponible());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              productoId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              nombre_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              stockDisponible_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object productoId_ = "";
    /**
     * <code>string producto_id = 1;</code>
     * @return The productoId.
     */
    public java.lang.String getProductoId() {
      java.lang.Object ref = productoId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productoId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string producto_id = 1;</code>
     * @return The bytes for productoId.
     */
    public com.google.protobuf.ByteString
        getProductoIdBytes() {
      java.lang.Object ref = productoId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string producto_id = 1;</code>
     * @param value The productoId to set.
     * @return This builder for chaining.
     */
    public Builder setProductoId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      productoId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string producto_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductoId() {
      productoId_ = getDefaultInstance().getProductoId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string producto_id = 1;</code>
     * @param value The bytes for productoId to set.
     * @return This builder for chaining.
     */
    public Builder setProductoIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      productoId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object nombre_ = "";
    /**
     * <code>string nombre = 2;</code>
     * @return The nombre.
     */
    public java.lang.String getNombre() {
      java.lang.Object ref = nombre_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nombre_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nombre = 2;</code>
     * @return The bytes for nombre.
     */
    public com.google.protobuf.ByteString
        getNombreBytes() {
      java.lang.Object ref = nombre_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nombre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nombre = 2;</code>
     * @param value The nombre to set.
     * @return This builder for chaining.
     */
    public Builder setNombre(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nombre_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string nombre = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNombre() {
      nombre_ = getDefaultInstance().getNombre();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string nombre = 2;</code>
     * @param value The bytes for nombre to set.
     * @return This builder for chaining.
     */
    public Builder setNombreBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nombre_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int stockDisponible_ ;
    /**
     * <code>int32 stock_disponible = 3;</code>
     * @return The stockDisponible.
     */
    @java.lang.Override
    public int getStockDisponible() {
      return stockDisponible_;
    }
    /**
     * <code>int32 stock_disponible = 3;</code>
     * @param value The stockDisponible to set.
     * @return This builder for chaining.
     */
    public Builder setStockDisponible(int value) {

      stockDisponible_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 stock_disponible = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStockDisponible() {
      bitField0_ = (bitField0_ & ~0x00000004);
      stockDisponible_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Inventario)
  }

  // @@protoc_insertion_point(class_scope:Inventario)
  private static final com.tienda.grpc.Inventario DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tienda.grpc.Inventario();
  }

  public static com.tienda.grpc.Inventario getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Inventario>
      PARSER = new com.google.protobuf.AbstractParser<Inventario>() {
    @java.lang.Override
    public Inventario parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Inventario> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Inventario> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tienda.grpc.Inventario getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

