// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: interfaz.proto
// Protobuf Java Version: 4.30.2

package com.tienda.grpc;

public interface InventarioOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Inventario)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string producto_id = 1;</code>
   * @return The productoId.
   */
  java.lang.String getProductoId();
  /**
   * <code>string producto_id = 1;</code>
   * @return The bytes for productoId.
   */
  com.google.protobuf.ByteString
      getProductoIdBytes();

  /**
   * <code>string nombre = 2;</code>
   * @return The nombre.
   */
  java.lang.String getNombre();
  /**
   * <code>string nombre = 2;</code>
   * @return The bytes for nombre.
   */
  com.google.protobuf.ByteString
      getNombreBytes();

  /**
   * <code>int32 stock_disponible = 3;</code>
   * @return The stockDisponible.
   */
  int getStockDisponible();
}
