// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: interfaz.proto
// Protobuf Java Version: 4.30.2

package com.tienda.grpc;

public interface ListarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * opcional, "" = todos
   * </pre>
   *
   * <code>string categoria = 1;</code>
   * @return The categoria.
   */
  java.lang.String getCategoria();
  /**
   * <pre>
   * opcional, "" = todos
   * </pre>
   *
   * <code>string categoria = 1;</code>
   * @return The bytes for categoria.
   */
  com.google.protobuf.ByteString
      getCategoriaBytes();
}
