// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: interfaz.proto
// Protobuf Java Version: 4.30.2

package com.tienda.grpc;

public interface RespuestaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Respuesta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool exito = 1;</code>
   * @return The exito.
   */
  boolean getExito();

  /**
   * <pre>
   * ej: "Producto agregado", "Error: no encontrado"
   * </pre>
   *
   * <code>string mensaje = 2;</code>
   * @return The mensaje.
   */
  java.lang.String getMensaje();
  /**
   * <pre>
   * ej: "Producto agregado", "Error: no encontrado"
   * </pre>
   *
   * <code>string mensaje = 2;</code>
   * @return The bytes for mensaje.
   */
  com.google.protobuf.ByteString
      getMensajeBytes();
}
