// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: interfaz.proto
// Protobuf Java Version: 4.30.2

package com.tienda.grpc;

/**
 * <pre>
 * Respuesta simple para agregar/eliminar
 * </pre>
 *
 * Protobuf type {@code Respuesta}
 */
public final class Respuesta extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Respuesta)
    RespuestaOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Respuesta.class.getName());
  }
  // Use Respuesta.newBuilder() to construct.
  private Respuesta(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Respuesta() {
    mensaje_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tienda.grpc.Interfaz.internal_static_Respuesta_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tienda.grpc.Interfaz.internal_static_Respuesta_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tienda.grpc.Respuesta.class, com.tienda.grpc.Respuesta.Builder.class);
  }

  public static final int EXITO_FIELD_NUMBER = 1;
  private boolean exito_ = false;
  /**
   * <code>bool exito = 1;</code>
   * @return The exito.
   */
  @java.lang.Override
  public boolean getExito() {
    return exito_;
  }

  public static final int MENSAJE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mensaje_ = "";
  /**
   * <pre>
   * ej: "Producto agregado", "Error: no encontrado"
   * </pre>
   *
   * <code>string mensaje = 2;</code>
   * @return The mensaje.
   */
  @java.lang.Override
  public java.lang.String getMensaje() {
    java.lang.Object ref = mensaje_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mensaje_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ej: "Producto agregado", "Error: no encontrado"
   * </pre>
   *
   * <code>string mensaje = 2;</code>
   * @return The bytes for mensaje.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMensajeBytes() {
    java.lang.Object ref = mensaje_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mensaje_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (exito_ != false) {
      output.writeBool(1, exito_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mensaje_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, mensaje_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (exito_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, exito_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mensaje_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, mensaje_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tienda.grpc.Respuesta)) {
      return super.equals(obj);
    }
    com.tienda.grpc.Respuesta other = (com.tienda.grpc.Respuesta) obj;

    if (getExito()
        != other.getExito()) return false;
    if (!getMensaje()
        .equals(other.getMensaje())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXITO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getExito());
    hash = (37 * hash) + MENSAJE_FIELD_NUMBER;
    hash = (53 * hash) + getMensaje().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tienda.grpc.Respuesta parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tienda.grpc.Respuesta parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tienda.grpc.Respuesta parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tienda.grpc.Respuesta parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tienda.grpc.Respuesta parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tienda.grpc.Respuesta parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tienda.grpc.Respuesta parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tienda.grpc.Respuesta parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tienda.grpc.Respuesta parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tienda.grpc.Respuesta parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tienda.grpc.Respuesta parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tienda.grpc.Respuesta parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tienda.grpc.Respuesta prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Respuesta simple para agregar/eliminar
   * </pre>
   *
   * Protobuf type {@code Respuesta}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Respuesta)
      com.tienda.grpc.RespuestaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tienda.grpc.Interfaz.internal_static_Respuesta_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tienda.grpc.Interfaz.internal_static_Respuesta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tienda.grpc.Respuesta.class, com.tienda.grpc.Respuesta.Builder.class);
    }

    // Construct using com.tienda.grpc.Respuesta.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      exito_ = false;
      mensaje_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tienda.grpc.Interfaz.internal_static_Respuesta_descriptor;
    }

    @java.lang.Override
    public com.tienda.grpc.Respuesta getDefaultInstanceForType() {
      return com.tienda.grpc.Respuesta.getDefaultInstance();
    }

    @java.lang.Override
    public com.tienda.grpc.Respuesta build() {
      com.tienda.grpc.Respuesta result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tienda.grpc.Respuesta buildPartial() {
      com.tienda.grpc.Respuesta result = new com.tienda.grpc.Respuesta(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tienda.grpc.Respuesta result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.exito_ = exito_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.mensaje_ = mensaje_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tienda.grpc.Respuesta) {
        return mergeFrom((com.tienda.grpc.Respuesta)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tienda.grpc.Respuesta other) {
      if (other == com.tienda.grpc.Respuesta.getDefaultInstance()) return this;
      if (other.getExito() != false) {
        setExito(other.getExito());
      }
      if (!other.getMensaje().isEmpty()) {
        mensaje_ = other.mensaje_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              exito_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              mensaje_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean exito_ ;
    /**
     * <code>bool exito = 1;</code>
     * @return The exito.
     */
    @java.lang.Override
    public boolean getExito() {
      return exito_;
    }
    /**
     * <code>bool exito = 1;</code>
     * @param value The exito to set.
     * @return This builder for chaining.
     */
    public Builder setExito(boolean value) {

      exito_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool exito = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExito() {
      bitField0_ = (bitField0_ & ~0x00000001);
      exito_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object mensaje_ = "";
    /**
     * <pre>
     * ej: "Producto agregado", "Error: no encontrado"
     * </pre>
     *
     * <code>string mensaje = 2;</code>
     * @return The mensaje.
     */
    public java.lang.String getMensaje() {
      java.lang.Object ref = mensaje_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensaje_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ej: "Producto agregado", "Error: no encontrado"
     * </pre>
     *
     * <code>string mensaje = 2;</code>
     * @return The bytes for mensaje.
     */
    public com.google.protobuf.ByteString
        getMensajeBytes() {
      java.lang.Object ref = mensaje_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensaje_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ej: "Producto agregado", "Error: no encontrado"
     * </pre>
     *
     * <code>string mensaje = 2;</code>
     * @param value The mensaje to set.
     * @return This builder for chaining.
     */
    public Builder setMensaje(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mensaje_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ej: "Producto agregado", "Error: no encontrado"
     * </pre>
     *
     * <code>string mensaje = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMensaje() {
      mensaje_ = getDefaultInstance().getMensaje();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ej: "Producto agregado", "Error: no encontrado"
     * </pre>
     *
     * <code>string mensaje = 2;</code>
     * @param value The bytes for mensaje to set.
     * @return This builder for chaining.
     */
    public Builder setMensajeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mensaje_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Respuesta)
  }

  // @@protoc_insertion_point(class_scope:Respuesta)
  private static final com.tienda.grpc.Respuesta DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tienda.grpc.Respuesta();
  }

  public static com.tienda.grpc.Respuesta getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Respuesta>
      PARSER = new com.google.protobuf.AbstractParser<Respuesta>() {
    @java.lang.Override
    public Respuesta parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Respuesta> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Respuesta> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tienda.grpc.Respuesta getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

